### ISSUE TITLE
PR contained an unknown status

### ISSUE THREAD

**Issue by Conky5** [Crazybus/pratus#9]
While trying to watch https://github.com/docker-library/official-images/pull/9902 I encountered this error:
```
Checking status of pull request 9902 in docker-library/official-images every 30 seconds

PR contained an unknown status: "pending"
```

**Comment by Crazybus** [comment]
Looks like a fun race condition

This part checks the individual statuses:

https://github.com/Crazybus/pratus/blob/68583531bb656e706a33b459a8b6f1e314bddca5/pratus.go#L100-L104


https://github.com/Crazybus/pratus/blob/68583531bb656e706a33b459a8b6f1e314bddca5/pratus.go#L41-L48

But combined state is calculated before this. So it was pending at the start of the loop but finished before checking each individual status. Fix incoming!

**Comment by Conky5** [comment]
Thank you!
